name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get update
    - name: Checkout tree
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "5.2"
        
    - run: opam install . --deps-only --with-test

    - run: opam exec -- dune fmt

    - run: zanuda -dir .

    - run: opam exec -- dune build --display=short @check -j3 || (if grep -q "Warning" dune.log; then exit 1; fi)

    - run: opam exec -- dune runtest
              
